-- ============================================================
-- Quality, GMP, Food Safety & Compliance Framework Seed
-- ============================================================
-- Adds 10 manufacturing/quality/food-safety frameworks and ~120
-- policy_control entries covering pharma, FMCG, and food.
-- These are evidence-check controls (no regex pattern) used by
-- the GRC module and the compliance dashboard.
-- ============================================================

DO $$
DECLARE
  who_gmp_id    uuid;
  fda_cgmp_id   uuid;
  eu_gmp_id     uuid;
  nafdac_gmp_id uuid;
  ich_q10_id    uuid;
  ich_q9_id     uuid;
  iso_9001_id   uuid;
  iso_22000_id  uuid;
  haccp_id      uuid;
  brcgs_id      uuid;
BEGIN

-- ── 1. Insert frameworks ─────────────────────────────────────────────────────
INSERT INTO public.regulatory_frameworks
  (code, name, short_name, jurisdiction, regulatory_body, version, description, sort_order)
VALUES
  ('who_gmp',
   'WHO Good Manufacturing Practice for Pharmaceutical Products',
   'WHO-GMP',
   'who',
   'World Health Organization',
   'TRS 986 / TRS 1010',
   'WHO GMP guidelines for pharmaceutical manufacturing — covers premises, equipment, personnel, production, QC, documentation, and self-inspection.',
   10),

  ('fda_cgmp',
   'FDA Current Good Manufacturing Practice — 21 CFR Parts 210 & 211',
   'FDA CGMP',
   'usa',
   'FDA (CDER / CBER)',
   '21 CFR 210 & 211',
   'US federal regulation governing the manufacturing, processing, packing, and holding of drugs and finished pharmaceuticals.',
   11),

  ('eu_gmp',
   'EU Good Manufacturing Practice — EudraLex Volume 4',
   'EU GMP',
   'europe',
   'European Medicines Agency / European Commission',
   'EudraLex Vol. 4 (2023)',
   'European Union GMP requirements for medicinal products for human and veterinary use. Covers basic requirements and annexes including Annex 15 (validation), Annex 16 (QP), Annex 11 (computerised systems).',
   12),

  ('nafdac_gmp',
   'NAFDAC Good Manufacturing Practice Guidelines',
   'NAFDAC GMP',
   'nigeria',
   'NAFDAC',
   '2021',
   'Nigeria-specific GMP requirements for pharmaceutical manufacturers, including site licensing, product registration, QP designation, and adverse drug reaction reporting obligations.',
   13),

  ('ich_q10',
   'ICH Q10 — Pharmaceutical Quality System',
   'ICH Q10',
   'global',
   'International Council for Harmonisation (ICH)',
   'Q10 (Step 4, 2008)',
   'ICH guideline defining the elements of an effective Pharmaceutical Quality System (PQS) across the product lifecycle — development, technology transfer, commercial manufacture, and discontinuation.',
   14),

  ('ich_q9',
   'ICH Q9 — Quality Risk Management',
   'ICH Q9',
   'global',
   'International Council for Harmonisation (ICH)',
   'Q9(R1) (Step 4, 2023)',
   'ICH guideline for quality risk management in pharmaceutical manufacturing. Provides principles and tools (FMEA, HAZOP, fault tree analysis) for identifying, assessing, controlling, and reviewing risks.',
   15),

  ('iso_9001',
   'ISO 9001:2015 — Quality Management Systems',
   'ISO 9001',
   'global',
   'International Organization for Standardization (ISO)',
   '9001:2015',
   'International standard specifying requirements for a quality management system. Applicable to any organisation regardless of size or industry. Risk-based thinking and process approach are central.',
   16),

  ('iso_22000',
   'ISO 22000:2018 — Food Safety Management Systems',
   'ISO 22000',
   'global',
   'International Organization for Standardization (ISO)',
   '22000:2018',
   'International standard for food safety management integrating HACCP principles with prerequisite programmes (PRPs). Applies to all organisations in the food chain including manufacturers, retailers, and packaging suppliers.',
   17),

  ('haccp',
   'HACCP — Hazard Analysis and Critical Control Points',
   'HACCP',
   'global',
   'Codex Alimentarius Commission / FAO / WHO',
   'CAC/RCP 1-1969 Rev. 4 (2003)',
   'Science-based food safety system identifying, evaluating, and controlling hazards significant to food safety. Seven principles form the core: hazard analysis, CCPs, critical limits, monitoring, corrective actions, verification, and record-keeping.',
   18),

  ('brcgs_food',
   'BRCGS Global Standard for Food Safety',
   'BRCGS Food',
   'global',
   'British Retail Consortium Global Standards (BRCGS)',
   'Issue 9 (2022)',
   'BRCGS Food Safety standard used by retailers and food service operators worldwide to audit and approve food manufacturers. Covers management commitment, HACCP, food safety culture, site standards, product control, and supplier management.',
   19)

ON CONFLICT (code) DO NOTHING;

-- ── Get IDs ──────────────────────────────────────────────────────────────────
SELECT id INTO who_gmp_id    FROM public.regulatory_frameworks WHERE code = 'who_gmp';
SELECT id INTO fda_cgmp_id   FROM public.regulatory_frameworks WHERE code = 'fda_cgmp';
SELECT id INTO eu_gmp_id     FROM public.regulatory_frameworks WHERE code = 'eu_gmp';
SELECT id INTO nafdac_gmp_id FROM public.regulatory_frameworks WHERE code = 'nafdac_gmp';
SELECT id INTO ich_q10_id    FROM public.regulatory_frameworks WHERE code = 'ich_q10';
SELECT id INTO ich_q9_id     FROM public.regulatory_frameworks WHERE code = 'ich_q9';
SELECT id INTO iso_9001_id   FROM public.regulatory_frameworks WHERE code = 'iso_9001';
SELECT id INTO iso_22000_id  FROM public.regulatory_frameworks WHERE code = 'iso_22000';
SELECT id INTO haccp_id      FROM public.regulatory_frameworks WHERE code = 'haccp';
SELECT id INTO brcgs_id      FROM public.regulatory_frameworks WHERE code = 'brcgs_food';

-- ── 2. WHO GMP Controls ───────────────────────────────────────────────────────
INSERT INTO public.framework_controls
  (framework_id, control_code, title, description, control_type, severity,
   regulation_cited, category, jurisdiction,
   pattern_source, pattern_flags, suggestion_template,
   trigger_patterns, required_phrases, platforms, audiences, is_active)
VALUES
  (who_gmp_id, 'WHO-GMP-001', 'Batch Manufacturing Record (BMR) completeness',
   'Every batch must have a complete, reviewed, and approved Batch Manufacturing Record before release.',
   'policy_control', 'Red',
   'WHO TRS 986, Annex 2, Section 15 — Production and In-Process Controls',
   'manufacturing_control', 'who', null, 'gi',
   'Upload the completed BMR for this batch, signed by production and reviewed by QA, with all in-process checks recorded.',
   null, null, null, null, true),

  (who_gmp_id, 'WHO-GMP-002', 'Qualified Person (QP) batch release certification',
   'Each batch must be certified by a designated Qualified Person before release to market.',
   'policy_control', 'Red',
   'WHO TRS 986, Annex 2, Section 17 — Quality Control',
   'manufacturing_control', 'who', null, 'gi',
   'Provide the QP release certificate for this batch including QP name, date, batch number, and statement of compliance.',
   null, null, null, null, true),

  (who_gmp_id, 'WHO-GMP-003', 'Deviation investigation and closure',
   'All manufacturing deviations must be documented, investigated for root cause, and closed with a CAPA within the defined timeframe.',
   'policy_control', 'Red',
   'WHO TRS 986, Annex 2, Section 9 — Complaints and Recalls / Section 15',
   'manufacturing_control', 'who', null, 'gi',
   'Provide the deviation report number, root cause analysis, assigned CAPA reference, and closure date.',
   null, null, null, null, true),

  (who_gmp_id, 'WHO-GMP-004', 'Corrective and Preventive Action (CAPA) system',
   'A documented CAPA system must be maintained. All CAPAs must have owners, due dates, and evidence of completion.',
   'policy_control', 'Red',
   'WHO TRS 986, Annex 2, Section 9',
   'quality_management', 'who', null, 'gi',
   'Provide the CAPA register extract showing open and closed CAPAs with effectiveness verification records.',
   null, null, null, null, true),

  (who_gmp_id, 'WHO-GMP-005', 'Environmental and microbiological monitoring',
   'Cleanroom environments must be monitored per a written schedule. Results must be trended and out-of-limit results investigated.',
   'policy_control', 'Red',
   'WHO TRS 986, Annex 2, Section 12 — Premises; Annex 1 (sterile)',
   'manufacturing_control', 'who', null, 'gi',
   'Provide the latest environmental monitoring report including viable/non-viable particulate results and trend analysis for the relevant cleanroom grade.',
   null, null, null, null, true),

  (who_gmp_id, 'WHO-GMP-006', 'Equipment qualification (IQ/OQ/PQ)',
   'All critical manufacturing equipment must have current Installation, Operational, and Performance Qualification documentation.',
   'policy_control', 'Yellow',
   'WHO TRS 986, Annex 2, Section 11 — Equipment',
   'manufacturing_control', 'who', null, 'gi',
   'Upload the current qualification summary or validation report for this equipment. Confirm requalification schedule is up to date.',
   null, null, null, null, true),

  (who_gmp_id, 'WHO-GMP-007', 'Change control for process, materials, or equipment',
   'All changes to approved manufacturing processes, starting materials, primary packaging, or critical equipment must pass through a documented change control system before implementation.',
   'policy_control', 'Red',
   'WHO TRS 986, Annex 2, Section 10 — Change Control',
   'manufacturing_control', 'who', null, 'gi',
   'Provide the change control record number, impact assessment, regulatory notification status (if applicable), and approval signatures.',
   null, null, null, null, true),

  (who_gmp_id, 'WHO-GMP-008', 'Stability programme maintenance',
   'An ongoing stability programme must be maintained for all marketed products. Results must be reviewed and any adverse trends investigated.',
   'policy_control', 'Yellow',
   'WHO TRS 986, Annex 2, Section 17.4 — Stability',
   'manufacturing_control', 'who', null, 'gi',
   'Provide the current stability protocol and latest stability data for this product. Confirm no adverse trends or shelf-life changes are pending.',
   null, null, null, null, true),

  (who_gmp_id, 'WHO-GMP-009', 'Supplier and material qualification',
   'All critical raw material and primary packaging suppliers must be qualified through audit, testing, or certification review before use.',
   'policy_control', 'Yellow',
   'WHO TRS 986, Annex 2, Section 14 — Materials Management',
   'manufacturing_control', 'who', null, 'gi',
   'Provide the approved supplier list entry for this material and evidence of last qualification audit or certificate review date.',
   null, null, null, null, true),

  (who_gmp_id, 'WHO-GMP-010', 'SOP review cycle compliance',
   'All SOPs must be reviewed at defined intervals (typically every 2–3 years) and reissued or retired as appropriate.',
   'policy_control', 'Yellow',
   'WHO TRS 986, Annex 2, Section 4 — Documentation',
   'quality_management', 'who', null, 'gi',
   'Confirm this SOP has been reviewed within the defined review period. Provide the current version number, review date, and approver.',
   null, null, null, null, true),

  (who_gmp_id, 'WHO-GMP-011', 'Training records completeness',
   'All personnel involved in manufacturing, QC, and warehouse operations must have current, documented training records including GMP refresher training.',
   'policy_control', 'Yellow',
   'WHO TRS 986, Annex 2, Section 6 — Personnel',
   'quality_management', 'who', null, 'gi',
   'Provide the training matrix extract showing GMP training completion status for all relevant personnel in the last 12 months.',
   null, null, null, null, true),

  (who_gmp_id, 'WHO-GMP-012', 'Product recall procedure and drill',
   'A documented product recall/withdrawal procedure must exist and must be tested at least annually via a mock recall.',
   'policy_control', 'Red',
   'WHO TRS 986, Annex 2, Section 9 — Complaints and Recalls',
   'regulatory_compliance', 'who', null, 'gi',
   'Provide the current recall SOP and last mock recall exercise report with results and identified gaps.',
   null, null, null, null, true),

  (who_gmp_id, 'WHO-GMP-013', 'Water system validation and ongoing monitoring',
   'Purified Water (PW) and Water for Injection (WFI) systems must be validated and monitored per a written sampling plan.',
   'policy_control', 'Red',
   'WHO TRS 986, Annex 2, Section 12; WHO TRS 970 Water for Pharmaceutical Use',
   'manufacturing_control', 'who', null, 'gi',
   'Provide the water system validation report (or summary) and last 3 months of routine water quality test results.',
   null, null, null, null, true),

  (who_gmp_id, 'WHO-GMP-014', 'Out-of-specification (OOS) investigation',
   'All out-of-specification laboratory results must be investigated using a formal OOS procedure to determine if the result is an assignable cause or a true product failure.',
   'policy_control', 'Red',
   'WHO TRS 986, Annex 2, Section 17 — Quality Control',
   'manufacturing_control', 'who', null, 'gi',
   'Provide the OOS investigation report number, Phase I/Phase II investigation conclusion, and disposition decision for the affected batch.',
   null, null, null, null, true),

  (who_gmp_id, 'WHO-GMP-015', 'Self-inspection programme',
   'A documented self-inspection programme must be maintained. Findings must be tracked to closure with CAPAs raised for deficiencies.',
   'policy_control', 'Yellow',
   'WHO TRS 986, Annex 2, Section 18 — Self Inspection',
   'audit', 'who', null, 'gi',
   'Provide the self-inspection schedule, last completed audit report, and CAPA tracking log with closure evidence.',
   null, null, null, null, true),

-- ── 3. FDA CGMP Controls (21 CFR 211) ────────────────────────────────────────
  (fda_cgmp_id, 'CFR211-001', 'Master Production and Control Records (MPR)',
   'A master production and control record must exist for each drug product that includes formulae, processing instructions, specifications, and sampling procedures.',
   'policy_control', 'Red',
   '21 CFR 211.186 — Master Production and Control Records',
   'manufacturing_control', 'usa', null, 'gi',
   'Provide the current approved Master Production Record for this product including version number, effective date, and change history.',
   null, null, null, null, true),

  (fda_cgmp_id, 'CFR211-002', 'Batch Production Records — accurate reproduction',
   'A batch production record must be prepared for each batch produced. It must be an accurate reproduction of the applicable MPR.',
   'policy_control', 'Red',
   '21 CFR 211.188 — Batch Production and Control Records',
   'manufacturing_control', 'usa', null, 'gi',
   'Upload the executed Batch Production Record for this batch showing all process steps, in-process checks, deviations, and operator signatures.',
   null, null, null, null, true),

  (fda_cgmp_id, 'CFR211-003', 'Laboratory controls — specifications and test methods',
   'Scientifically sound and appropriate specifications, standards, sampling plans, and test procedures must be established for drug components, containers, closures, and finished products.',
   'policy_control', 'Red',
   '21 CFR 211.160 — Laboratory Controls: General Requirements',
   'manufacturing_control', 'usa', null, 'gi',
   'Provide the approved specification sheet and validated test method reference for this material or product. Include method validation report if applicable.',
   null, null, null, null, true),

  (fda_cgmp_id, 'CFR211-004', 'Incoming component testing and approval',
   'Each lot of drug components, containers, and closures must be withheld from use until sampled, tested, and released by QC.',
   'policy_control', 'Red',
   '21 CFR 211.84 — Testing and Approval or Rejection of Components, Drug Product Containers, and Closures',
   'manufacturing_control', 'usa', null, 'gi',
   'Provide the CoA and internal QC test results for this component lot. Confirm QC approval/rejection status and label record.',
   null, null, null, null, true),

  (fda_cgmp_id, 'CFR211-005', 'Equipment cleaning and maintenance records',
   'Written procedures for equipment cleaning and maintenance must exist. Records must be maintained showing dates, times, and signatures for each cleaning and maintenance activity.',
   'policy_control', 'Yellow',
   '21 CFR 211.67 — Equipment Cleaning and Maintenance',
   'manufacturing_control', 'usa', null, 'gi',
   'Provide the equipment logbook extract showing the last three cleaning records for this piece of equipment, including cleaning agent, method, and operator signature.',
   null, null, null, null, true),

  (fda_cgmp_id, 'CFR211-006', 'Production record review before batch release',
   'Production and control records for each batch shall be reviewed and approved by the quality control unit before release or distribution.',
   'policy_control', 'Red',
   '21 CFR 211.192 — Production Record Review',
   'manufacturing_control', 'usa', null, 'gi',
   'Confirm QU review and approval signature on the batch production record. Provide the QU release decision and date.',
   null, null, null, null, true),

  (fda_cgmp_id, 'CFR211-007', 'OOS result investigation',
   'Any unexplained discrepancy or failure of a batch to meet specification shall be thoroughly investigated, including a review of the production record.',
   'policy_control', 'Red',
   '21 CFR 211.192 — OOS Investigation Requirement',
   'manufacturing_control', 'usa', null, 'gi',
   'Provide the completed OOS investigation report referencing FDA''s 2006 OOS Guidance. Include Phase I lab investigation and Phase II manufacturing investigation if conducted.',
   null, null, null, null, true),

  (fda_cgmp_id, 'CFR211-008', 'Annual Product Review (APR)',
   'An annual written review of each drug product must be conducted to assess quality standards, investigate any unexplained discrepancies, and identify corrective actions.',
   'policy_control', 'Yellow',
   '21 CFR 211.180(e) — Annual Review',
   'quality_management', 'usa', null, 'gi',
   'Provide the most recent Annual Product Review report for this product. Confirm all required elements (batch failures, OOS results, CAPAs, complaints, stability) are addressed.',
   null, null, null, null, true),

  (fda_cgmp_id, 'CFR211-009', 'Reserve sample retention',
   'Reserve samples must be retained for each lot of drug product. Retention period is one year after expiry date of the lot.',
   'policy_control', 'Yellow',
   '21 CFR 211.170 — Reserve Samples',
   'manufacturing_control', 'usa', null, 'gi',
   'Confirm reserve sample is retained for this batch with appropriate quantity, storage conditions, and expiry date. Provide reserve sample log entry.',
   null, null, null, null, true),

  (fda_cgmp_id, 'CFR211-010', 'Written procedures for all production operations',
   'Written procedures must be established and followed for all operations in the manufacture, processing, packing, and holding of drug products.',
   'policy_control', 'Red',
   '21 CFR 211.100(a) — Written Procedures; Deviations',
   'quality_management', 'usa', null, 'gi',
   'Confirm the relevant SOP is current (reviewed within the review cycle), approved, and that all operators performing this task have completed training on the current version.',
   null, null, null, null, true),

  (fda_cgmp_id, 'CFR211-011', 'Complaint handling and investigation',
   'All product complaints must be received, evaluated, and investigated. Those involving possible product defects must be reviewed according to written procedures.',
   'policy_control', 'Yellow',
   '21 CFR 211.198 — Complaint Files',
   'regulatory_compliance', 'usa', null, 'gi',
   'Provide the complaint investigation report and disposition. Confirm MDR/field alert reporting obligation was evaluated.',
   null, null, null, null, true),

-- ── 4. EU GMP Controls ────────────────────────────────────────────────────────
  (eu_gmp_id, 'EUGMP-001', 'Qualified Person (QP) batch certification — Annex 16',
   'Before a batch is released for sale in the EU, it must be certified by a Qualified Person who confirms it was manufactured and tested in compliance with EU law.',
   'policy_control', 'Red',
   'EudraLex Vol. 4, Annex 16 — Certification by a Qualified Person',
   'manufacturing_control', 'europe', null, 'gi',
   'Provide the QP batch certification statement including QP name, EU QP registration number, declaration text, and date for this batch.',
   null, null, null, null, true),

  (eu_gmp_id, 'EUGMP-002', 'Product Quality Review (PQR)',
   'A Product Quality Review must be conducted for each authorised medicinal product at regular intervals (typically annually) to verify process consistency and identify improvements.',
   'policy_control', 'Yellow',
   'EudraLex Vol. 4, Chapter 1, Section 1.10 — Product Quality Review',
   'quality_management', 'europe', null, 'gi',
   'Provide the most recent PQR report. Confirm it covers all required elements: batch analysis, OOS results, deviations, CAPAs, changes, stability, and returns/complaints.',
   null, null, null, null, true),

  (eu_gmp_id, 'EUGMP-003', 'Process validation and continued process verification',
   'Manufacturing processes must be validated before release of finished product. Continued process verification must demonstrate the process remains in a state of control.',
   'policy_control', 'Red',
   'EudraLex Vol. 4, Annex 15 — Qualification and Validation',
   'manufacturing_control', 'europe', null, 'gi',
   'Provide the process validation protocol and report (or CPV statistical summary for established processes). Confirm validation status is current.',
   null, null, null, null, true),

  (eu_gmp_id, 'EUGMP-004', 'Computerised system validation (CSV)',
   'Computerised systems used in GMP activities must be validated. Validation documentation must demonstrate fitness for intended purpose.',
   'policy_control', 'Yellow',
   'EudraLex Vol. 4, Annex 11 — Computerised Systems',
   'manufacturing_control', 'europe', null, 'gi',
   'Provide the validation summary report for this system including GAMP 5 category, validation approach, and confirmation of current validated state.',
   null, null, null, null, true),

  (eu_gmp_id, 'EUGMP-005', 'Self-inspection programme — Chapter 9',
   'Regular self-inspections must be performed to monitor the implementation and compliance with GMP principles and to propose necessary corrective actions.',
   'policy_control', 'Yellow',
   'EudraLex Vol. 4, Chapter 9 — Self Inspection',
   'audit', 'europe', null, 'gi',
   'Provide the self-inspection programme schedule, last completed inspection report, and CAPA log with open/closed status.',
   null, null, null, null, true),

  (eu_gmp_id, 'EUGMP-006', 'Complaints and recalls system',
   'All quality complaints must be recorded and investigated. A recall system must be in place to enable the rapid and effective withdrawal of any product from the market.',
   'policy_control', 'Red',
   'EudraLex Vol. 4, Chapter 8 — Complaints, Quality Defects and Product Recalls',
   'regulatory_compliance', 'europe', null, 'gi',
   'Provide the complaint SOP and recall SOP references. For any active complaint, provide the investigation report and MHRA/EMA notification status if applicable.',
   null, null, null, null, true),

  (eu_gmp_id, 'EUGMP-007', 'Technical agreements with contract manufacturers',
   'Written technical agreements must exist between the contract giver and contract acceptor defining GMP responsibilities for contract manufacturing and testing.',
   'policy_control', 'Yellow',
   'EudraLex Vol. 4, Chapter 7 — Outsourced Activities',
   'manufacturing_control', 'europe', null, 'gi',
   'Provide the current signed technical agreement with this contract manufacturer/laboratory. Confirm it has been reviewed within the last 3 years.',
   null, null, null, null, true),

  (eu_gmp_id, 'EUGMP-008', 'Returned goods assessment before re-release',
   'Returned medicinal products must not be placed back on the market without thorough evaluation by the Quality Unit.',
   'policy_control', 'Yellow',
   'EudraLex Vol. 4, Chapter 8.8 — Returned Medicinal Products',
   'manufacturing_control', 'europe', null, 'gi',
   'Provide the returned goods assessment report for this batch including storage condition verification, physical inspection results, and QU disposition decision.',
   null, null, null, null, true),

-- ── 5. NAFDAC GMP Controls ────────────────────────────────────────────────────
  (nafdac_gmp_id, 'NAFDAC-GMP-001', 'Current NAFDAC manufacturing site licence',
   'The manufacturing site must hold a current, valid NAFDAC manufacturing licence. Expired licences invalidate all batches manufactured at the site.',
   'policy_control', 'Red',
   'NAFDAC Act Cap N1 LFN 2004, Section 5 — Licensing of Premises',
   'regulatory_compliance', 'nigeria', null, 'gi',
   'Upload the current NAFDAC Site Manufacturing Licence. Confirm the expiry date is more than 3 months away and renewal application has been submitted if within 6 months of expiry.',
   null, null, null, null, true),

  (nafdac_gmp_id, 'NAFDAC-GMP-002', 'NAFDAC product registration certificate',
   'Every product manufactured for sale in Nigeria must be registered with NAFDAC. Unregistered products are prohibited.',
   'policy_control', 'Red',
   'NAFDAC Act Cap N1 LFN 2004, Section 10 — Registration of Products',
   'regulatory_compliance', 'nigeria', null, 'gi',
   'Provide the NAFDAC product registration certificate for this product. Confirm the registration number matches the product label and that the certificate is not expired.',
   null, null, null, null, true),

  (nafdac_gmp_id, 'NAFDAC-GMP-003', 'Superintendent Pharmacist designation',
   'Every pharmaceutical manufacturing facility must have a designated Superintendent Pharmacist registered with the Pharmacists Council of Nigeria (PCN).',
   'policy_control', 'Red',
   'Pharmacists Council of Nigeria Act Cap P17 LFN 2004, Section 15',
   'regulatory_compliance', 'nigeria', null, 'gi',
   'Provide the name and PCN registration number of the current Superintendent Pharmacist, and confirmation they are present at the facility during manufacturing operations.',
   null, null, null, null, true),

  (nafdac_gmp_id, 'NAFDAC-GMP-004', 'Current NAFDAC GMP certificate',
   'The manufacturing facility must hold a current NAFDAC GMP certificate issued following a satisfactory NAFDAC inspection.',
   'policy_control', 'Red',
   'NAFDAC Good Manufacturing Practice Regulations 2021',
   'regulatory_compliance', 'nigeria', null, 'gi',
   'Upload the current NAFDAC GMP certificate. Confirm the inspection date and certificate validity period. If expired or due within 6 months, confirm reinspection has been requested.',
   null, null, null, null, true),

  (nafdac_gmp_id, 'NAFDAC-GMP-005', 'Serious Adverse Drug Reaction (ADR) reporting',
   'Serious and unexpected adverse drug reactions must be reported to NAFDAC within 7 calendar days (fatal/life-threatening) or 15 days (other serious unexpected reactions).',
   'policy_control', 'Red',
   'NAFDAC Pharmacovigilance Guidelines 2021, Section 6 — ADR Reporting Timelines',
   'regulatory_compliance', 'nigeria', null, 'gi',
   'Provide the NAFDAC ADR report reference number and submission date for this event. Confirm it was submitted within the required timeframe.',
   null, null, null, null, true),

  (nafdac_gmp_id, 'NAFDAC-GMP-006', 'Product recall notification to NAFDAC',
   'Any product recall or market withdrawal must be reported to NAFDAC within 24 hours of the decision to recall.',
   'policy_control', 'Red',
   'NAFDAC Product Recall Guidelines 2019, Section 3.2',
   'regulatory_compliance', 'nigeria', null, 'gi',
   'Provide evidence of NAFDAC recall notification (acknowledgement letter or email), recall classification, and current recall status report.',
   null, null, null, null, true),

  (nafdac_gmp_id, 'NAFDAC-GMP-007', 'Annual returns filing',
   'Manufacturers must file annual returns with NAFDAC for each registered product, including batch production data and post-market surveillance information.',
   'policy_control', 'Yellow',
   'NAFDAC Products (Registration, Etc.) Regulations 2019, Regulation 24',
   'regulatory_compliance', 'nigeria', null, 'gi',
   'Provide the NAFDAC annual returns submission receipt for the current year for all registered products at this site.',
   null, null, null, null, true),

  (nafdac_gmp_id, 'NAFDAC-GMP-008', 'Post-Market Surveillance (PMS) compliance',
   'Manufacturers must participate in NAFDAC post-market surveillance activities and respond to any PMS findings within the specified timeframe.',
   'policy_control', 'Yellow',
   'NAFDAC Post-Market Surveillance Policy 2020',
   'regulatory_compliance', 'nigeria', null, 'gi',
   'Confirm no outstanding NAFDAC PMS notifications for this product. If any, provide response submission evidence and corrective action plan.',
   null, null, null, null, true),

-- ── 6. ICH Q10 Controls ───────────────────────────────────────────────────────
  (ich_q10_id, 'ICHQ10-001', 'Pharmaceutical Quality System (PQS) documentation',
   'The PQS must be defined, documented, and communicated to all relevant personnel. A Quality Manual or equivalent document should describe the PQS.',
   'policy_control', 'Yellow',
   'ICH Q10, Section 4 — PQS Documentation',
   'quality_management', 'global', null, 'gi',
   'Provide the current Quality Manual or PQS description document including scope, quality policy, QMS processes, and management responsibilities.',
   null, null, null, null, true),

  (ich_q10_id, 'ICHQ10-002', 'Senior management quality commitment and review',
   'Senior management must demonstrate commitment to the PQS through defined resource allocation, quality objectives, management review, and personal engagement with quality issues.',
   'policy_control', 'Yellow',
   'ICH Q10, Section 2 — Management Responsibilities',
   'quality_management', 'global', null, 'gi',
   'Provide the Management Review meeting minutes for the last review cycle, including quality KPIs reviewed, decisions made, and resource commitments.',
   null, null, null, null, true),

  (ich_q10_id, 'ICHQ10-003', 'Annual Product Quality Review (APQR)',
   'A formal review of each product at defined intervals should be conducted to verify consistency and identify areas for improvement.',
   'policy_control', 'Yellow',
   'ICH Q10, Section 4.4 — APQR',
   'quality_management', 'global', null, 'gi',
   'Provide the most recent APQR for this product. Confirm it covers batch disposition, OOS events, stability, complaints, CAPAs, and regulatory commitments.',
   null, null, null, null, true),

  (ich_q10_id, 'ICHQ10-004', 'Knowledge management throughout product lifecycle',
   'The organisation must manage knowledge about the manufacturing process, including design space, process understanding, and control strategy documentation.',
   'policy_control', 'Yellow',
   'ICH Q10, Section 1.5 — Knowledge Management',
   'quality_management', 'global', null, 'gi',
   'Provide the process knowledge repository reference (e.g., Development Report, Technology Transfer Report, or Process Description) demonstrating the current level of process understanding.',
   null, null, null, null, true),

  (ich_q10_id, 'ICHQ10-005', 'Post-approval change management system',
   'A system must be in place to manage changes after regulatory approval, assessing the need for additional studies and regulatory submissions before implementation.',
   'policy_control', 'Red',
   'ICH Q10, Section 3.2.3 — Change Management',
   'manufacturing_control', 'global', null, 'gi',
   'Provide the change control record for this change including impact category, regulatory filing requirement determination, and approval status before implementation.',
   null, null, null, null, true),

  (ich_q10_id, 'ICHQ10-006', 'Continual improvement monitoring',
   'The organisation must demonstrate a systematic approach to identifying and implementing process and quality improvements.',
   'policy_control', 'Yellow',
   'ICH Q10, Section 3 — Continual Improvement',
   'quality_management', 'global', null, 'gi',
   'Provide examples of improvement initiatives identified through APQR, trend analysis, or innovation in the last 12 months, with measurable outcomes.',
   null, null, null, null, true),

-- ── 7. ICH Q9 Controls ───────────────────────────────────────────────────────
  (ich_q9_id, 'ICHQ9-001', 'Quality risk management process documented and applied',
   'A formal QRM process must be in place for identifying, assessing, controlling, communicating, and reviewing risks to product quality throughout the product lifecycle.',
   'policy_control', 'Yellow',
   'ICH Q9(R1), Section 3 — General Quality Risk Management Process',
   'quality_management', 'global', null, 'gi',
   'Provide the risk assessment document (FMEA, risk register, or equivalent) for this process or change. Confirm it was reviewed by a qualified team and risk acceptance was documented.',
   null, null, null, null, true),

  (ich_q9_id, 'ICHQ9-002', 'Risk assessment tool selection and application',
   'The risk management tool chosen (FMEA, HACCP, fault tree, etc.) must be appropriate for the complexity of the problem and documented with rationale.',
   'policy_control', 'Yellow',
   'ICH Q9(R1), Annex I — Risk Management Methods and Tools',
   'quality_management', 'global', null, 'gi',
   'Confirm the risk assessment tool used is identified and justified. Provide the completed risk assessment output (RPN scores, risk ranking, or equivalent).',
   null, null, null, null, true),

  (ich_q9_id, 'ICHQ9-003', 'Risk review and update after change or deviation',
   'Risk assessments must be reviewed and updated following changes to the process, unexpected deviations, or new information that may alter the risk profile.',
   'policy_control', 'Yellow',
   'ICH Q9(R1), Section 3.2 — Risk Review',
   'quality_management', 'global', null, 'gi',
   'Confirm the existing risk assessment was reviewed following this change or event. Provide the updated risk assessment version with review rationale.',
   null, null, null, null, true),

-- ── 8. ISO 9001 Controls ─────────────────────────────────────────────────────
  (iso_9001_id, 'ISO9001-001', 'Context of the organisation — issue identification',
   'The organisation must determine external and internal issues relevant to its purpose and strategic direction that affect its ability to achieve QMS objectives.',
   'policy_control', 'Yellow',
   'ISO 9001:2015, Clause 4.1 — Understanding the Organisation and its Context',
   'quality_management', 'global', null, 'gi',
   'Provide the context analysis document (SWOT, PESTLE, or equivalent) identifying internal and external issues. Confirm it was last reviewed within 12 months.',
   null, null, null, null, true),

  (iso_9001_id, 'ISO9001-002', 'Quality Policy — documented and communicated',
   'Top management must establish, implement, and maintain a quality policy appropriate to the organisation''s context and strategic direction.',
   'policy_control', 'Yellow',
   'ISO 9001:2015, Clause 5.2 — Policy',
   'quality_management', 'global', null, 'gi',
   'Provide the current signed Quality Policy. Confirm it is displayed at the site, communicated to all personnel, and available to interested parties.',
   null, null, null, null, true),

  (iso_9001_id, 'ISO9001-003', 'Measurable quality objectives established',
   'The organisation must establish quality objectives at relevant functions, levels, and processes, which must be measurable, monitored, and updated as required.',
   'policy_control', 'Yellow',
   'ISO 9001:2015, Clause 6.2 — Quality Objectives',
   'quality_management', 'global', null, 'gi',
   'Provide the quality objectives register for the current period. Confirm each objective has a measurable target, owner, and progress indicator (KPI).',
   null, null, null, null, true),

  (iso_9001_id, 'ISO9001-004', 'Document and record control',
   'Documented information required by the QMS must be controlled to ensure it is available, suitable for use, and adequately protected.',
   'policy_control', 'Yellow',
   'ISO 9001:2015, Clause 7.5 — Documented Information',
   'quality_management', 'global', null, 'gi',
   'Confirm the document control procedure is current. Verify the document in question is the latest approved version via the document register.',
   null, null, null, null, true),

  (iso_9001_id, 'ISO9001-005', 'Internal audit programme and completion',
   'The organisation must conduct internal audits at planned intervals to determine if the QMS conforms to requirements and is effectively implemented.',
   'policy_control', 'Yellow',
   'ISO 9001:2015, Clause 9.2 — Internal Audit',
   'audit', 'global', null, 'gi',
   'Provide the internal audit programme for the current year and confirm audits are being completed per schedule. Provide the last completed audit report.',
   null, null, null, null, true),

  (iso_9001_id, 'ISO9001-006', 'Management review — inputs and outputs documented',
   'Top management must review the QMS at planned intervals to ensure its continuing suitability, adequacy, effectiveness, and alignment with strategic direction.',
   'policy_control', 'Yellow',
   'ISO 9001:2015, Clause 9.3 — Management Review',
   'quality_management', 'global', null, 'gi',
   'Provide the last management review minutes. Confirm all required inputs were addressed and outputs (decisions and actions) were recorded with owners and due dates.',
   null, null, null, null, true),

  (iso_9001_id, 'ISO9001-007', 'Nonconformity and corrective action tracking',
   'Nonconformities must be documented, root causes analysed, corrective actions implemented, and effectiveness verified.',
   'policy_control', 'Yellow',
   'ISO 9001:2015, Clause 10.2 — Nonconformity and Corrective Action',
   'quality_management', 'global', null, 'gi',
   'Provide the NCR/CAPA register extract for the last review period. Confirm all open items have owners and due dates, and closed items have effectiveness checks.',
   null, null, null, null, true),

  (iso_9001_id, 'ISO9001-008', 'Monitoring and measurement equipment — calibration',
   'Measurement equipment used to verify product or service conformance must be calibrated or verified at specified intervals against measurement standards traceable to international standards.',
   'policy_control', 'Yellow',
   'ISO 9001:2015, Clause 7.1.5 — Monitoring and Measuring Resources',
   'manufacturing_control', 'global', null, 'gi',
   'Provide the calibration record for this instrument. Confirm the certificate is current and traceable. Check that the calibration due date has not passed.',
   null, null, null, null, true),

  (iso_9001_id, 'ISO9001-009', 'External provider evaluation and re-evaluation',
   'Criteria for selection, evaluation, and re-evaluation of external providers must be established. Results and necessary actions must be recorded.',
   'policy_control', 'Yellow',
   'ISO 9001:2015, Clause 8.4 — Control of Externally Provided Processes, Products and Services',
   'quality_management', 'global', null, 'gi',
   'Provide the approved supplier register entry for this supplier including last evaluation score/date and any re-evaluation requirement.',
   null, null, null, null, true),

  (iso_9001_id, 'ISO9001-010', 'Customer satisfaction monitoring',
   'The organisation must monitor customers'' perception of the degree to which their needs and expectations have been fulfilled.',
   'policy_control', 'Yellow',
   'ISO 9001:2015, Clause 9.1.2 — Customer Satisfaction',
   'quality_management', 'global', null, 'gi',
   'Provide the latest customer satisfaction survey results or complaint/feedback analysis, including trend data and any resulting improvement actions.',
   null, null, null, null, true),

-- ── 9. ISO 22000 Food Safety Controls ────────────────────────────────────────
  (iso_22000_id, 'ISO22K-001', 'HACCP plan documented and implemented',
   'The organisation must establish, implement, maintain, and update a HACCP plan based on the hazard analysis.',
   'policy_control', 'Red',
   'ISO 22000:2018, Clause 8.5.4 — HACCP Plan',
   'food_safety', 'global', null, 'gi',
   'Provide the current HACCP plan document showing all CCPs, critical limits, monitoring procedures, corrective actions, and responsible persons.',
   null, null, null, null, true),

  (iso_22000_id, 'ISO22K-002', 'Prerequisite Programmes (PRPs) established',
   'PRPs appropriate to the organisation and its context in the food chain must be established, implemented, maintained, and updated.',
   'policy_control', 'Yellow',
   'ISO 22000:2018, Clause 8.2 — Prerequisite Programmes',
   'food_safety', 'global', null, 'gi',
   'Provide the PRP documentation package. Confirm it covers infrastructure, cleaning & disinfection, pest control, personnel hygiene, and allergen management.',
   null, null, null, null, true),

  (iso_22000_id, 'ISO22K-003', 'Food safety hazard analysis — all hazards identified',
   'All food safety hazards reasonably expected to occur must be identified considering the type of product, type of process, and actual process steps.',
   'policy_control', 'Red',
   'ISO 22000:2018, Clause 8.5.2 — Hazard Analysis',
   'food_safety', 'global', null, 'gi',
   'Provide the hazard analysis table covering biological, chemical (including allergens and veterinary drug residues), physical, and radiological hazards for this product.',
   null, null, null, null, true),

  (iso_22000_id, 'ISO22K-004', 'Critical Control Points — limits and monitoring defined',
   'For each CCP, critical limits must be established that separate acceptable from unacceptable. Monitoring procedures must ensure the CCP is under control.',
   'policy_control', 'Red',
   'ISO 22000:2018, Clause 8.5.4 — Critical Control Points and Critical Limits',
   'food_safety', 'global', null, 'gi',
   'Provide the CCP monitoring log for the production period under review. Confirm critical limits were not exceeded, or provide corrective action records where they were.',
   null, null, null, null, true),

  (iso_22000_id, 'ISO22K-005', 'Traceability system — raw materials to finished product',
   'The organisation must establish a traceability system to identify product lots and their relation to raw materials and processing records.',
   'policy_control', 'Red',
   'ISO 22000:2018, Clause 8.3 — Traceability',
   'food_safety', 'global', null, 'gi',
   'Demonstrate traceability by providing the traceability test report: starting from the finished product lot, trace back to all raw material lots and forward to distribution records.',
   null, null, null, null, true),

  (iso_22000_id, 'ISO22K-006', 'Allergen management and control',
   'Allergen risk must be assessed and control measures implemented to prevent cross-contact and ensure accurate allergen labelling.',
   'policy_control', 'Red',
   'ISO 22000:2018, Clause 8.2 / PAS 96:2017 — Allergen Management',
   'food_safety', 'global', null, 'gi',
   'Provide the allergen risk assessment for this product or line. Confirm cleaning validation for allergen removal, segregation measures, and label accuracy review.',
   null, null, null, null, true),

  (iso_22000_id, 'ISO22K-007', 'Verification activities — validation and system effectiveness',
   'Verification activities must confirm that PRPs are implemented and effective, the hazard analysis is updated, OPRPs and HACCP plan are implemented and effective.',
   'policy_control', 'Yellow',
   'ISO 22000:2018, Clause 8.8 — Verification Related to PRPs and the HACCP Plan',
   'food_safety', 'global', null, 'gi',
   'Provide the verification schedule and most recent verification activity records (microbiological product testing, environmental monitoring, process checks, or audit).',
   null, null, null, null, true),

  (iso_22000_id, 'ISO22K-008', 'Handling of potentially unsafe products',
   'Products that may not meet food safety requirements must be prevented from entering the food chain. Disposition decisions must be documented.',
   'policy_control', 'Red',
   'ISO 22000:2018, Clause 8.9.2 — Handling of Potentially Unsafe Products',
   'food_safety', 'global', null, 'gi',
   'Provide the nonconforming product record for this incident, including hold/quarantine action taken, evaluation results, and final disposition decision (destroy, reprocess, or divert).',
   null, null, null, null, true),

  (iso_22000_id, 'ISO22K-009', 'Emergency preparedness and response',
   'Procedures must be established for potential emergency situations or accidents with food safety impact.',
   'policy_control', 'Yellow',
   'ISO 22000:2018, Clause 8.4.2 — Emergency Preparedness and Response',
   'food_safety', 'global', null, 'gi',
   'Confirm emergency response procedures cover product recall, contamination events, facility incidents, and supplier failure. Provide last drill or test exercise report.',
   null, null, null, null, true),

  (iso_22000_id, 'ISO22K-010', 'Supplier and externally provided process control',
   'All externally provided materials and services that affect food safety must be controlled through specifications, monitoring, and supplier evaluation.',
   'policy_control', 'Yellow',
   'ISO 22000:2018, Clause 7.1.6 — Control of Externally Provided Processes, Products or Services',
   'food_safety', 'global', null, 'gi',
   'Provide the approved supplier register entry, current specification for this material, and evidence of last incoming inspection or CoA review.',
   null, null, null, null, true),

-- ── 10. HACCP Controls ───────────────────────────────────────────────────────
  (haccp_id, 'HACCP-001', 'Principle 1 — Hazard analysis conducted',
   'A list of all hazards associated with each process step must be developed, along with consideration of control measures.',
   'policy_control', 'Red',
   'Codex Alimentarius CAC/RCP 1-1969 Rev. 4, Principle 1',
   'food_safety', 'global', null, 'gi',
   'Provide the hazard analysis worksheet showing all process steps, identified hazards (biological, chemical, physical), likelihood and severity assessments, and control measures.',
   null, null, null, null, true),

  (haccp_id, 'HACCP-002', 'Principle 2 — Critical Control Points identified using decision tree',
   'CCPs must be identified using a structured decision tree approach to determine which hazards require control at a CCP.',
   'policy_control', 'Red',
   'Codex Alimentarius CAC/RCP 1-1969 Rev. 4, Principle 2',
   'food_safety', 'global', null, 'gi',
   'Provide the CCP determination worksheet showing the decision tree applied at each process step and the rationale for CCP designation or rejection.',
   null, null, null, null, true),

  (haccp_id, 'HACCP-003', 'Principle 3 — Critical limits established and validated',
   'Critical limits, which separate acceptability from unacceptability, must be established for each CCP. Limits must be validated against scientific references.',
   'policy_control', 'Red',
   'Codex Alimentarius CAC/RCP 1-1969 Rev. 4, Principle 3',
   'food_safety', 'global', null, 'gi',
   'Provide the CCP critical limit definitions with the scientific validation or regulatory reference for each limit (e.g., internal temperature ≥75°C referenced to pathogen reduction data).',
   null, null, null, null, true),

  (haccp_id, 'HACCP-004', 'Principle 4 — Monitoring system for each CCP',
   'A monitoring system must be established for each CCP. Monitoring procedures must be able to detect a loss of control.',
   'policy_control', 'Red',
   'Codex Alimentarius CAC/RCP 1-1969 Rev. 4, Principle 4',
   'food_safety', 'global', null, 'gi',
   'Provide the CCP monitoring records for the production run. Confirm frequency of monitoring is as documented and the responsible person has signed each record.',
   null, null, null, null, true),

  (haccp_id, 'HACCP-005', 'Principle 5 — Corrective actions for CCP deviations',
   'Specific corrective actions must be established for each CCP for use when monitoring indicates a critical limit has been exceeded.',
   'policy_control', 'Red',
   'Codex Alimentarius CAC/RCP 1-1969 Rev. 4, Principle 5',
   'food_safety', 'global', null, 'gi',
   'For each CCP deviation, provide the completed corrective action record including: cause identification, product disposition, action to restore control, and responsible person.',
   null, null, null, null, true),

  (haccp_id, 'HACCP-006', 'Principle 6 — Verification procedures conducted',
   'Verification procedures must be established to confirm the HACCP system is working effectively. This includes audits, product testing, and review of monitoring records.',
   'policy_control', 'Yellow',
   'Codex Alimentarius CAC/RCP 1-1969 Rev. 4, Principle 6',
   'food_safety', 'global', null, 'gi',
   'Provide the latest HACCP system verification report including records review findings, product testing results, and corrective actions raised.',
   null, null, null, null, true),

  (haccp_id, 'HACCP-007', 'Principle 7 — Documentation and record keeping',
   'Efficient and accurate record keeping is essential to the application of HACCP. All HACCP documents and records must be retained for a defined period.',
   'policy_control', 'Yellow',
   'Codex Alimentarius CAC/RCP 1-1969 Rev. 4, Principle 7',
   'food_safety', 'global', null, 'gi',
   'Confirm all HACCP records (monitoring, deviations, corrective actions, verification) are complete, legible, signed, and retained per the document retention schedule.',
   null, null, null, null, true),

  (haccp_id, 'HACCP-008', 'HACCP team — multidisciplinary and trained',
   'A multidisciplinary HACCP team must be assembled with relevant expertise covering the product, process, and hazard types being assessed.',
   'policy_control', 'Yellow',
   'Codex Alimentarius CAC/RCP 1-1969 Rev. 4, Preliminary Step 2',
   'food_safety', 'global', null, 'gi',
   'Provide the HACCP team composition record showing members, their departmental roles, and evidence of HACCP training completion for each member.',
   null, null, null, null, true),

-- ── 11. BRCGS Food Safety Controls ───────────────────────────────────────────
  (brcgs_id, 'BRCGS-001', 'Senior management commitment — policy signed and communicated',
   'Senior management must demonstrate their commitment to achieving BRCGS certification and to continuous improvement through a signed, communicated food safety policy.',
   'policy_control', 'Red',
   'BRCGS Food Issue 9, Clause 1.1 — Senior Management Commitment',
   'food_safety', 'global', null, 'gi',
   'Provide the signed food safety and quality policy (signed by site director/CEO) and evidence it has been communicated to all staff (e.g., training record or notice board photo).',
   null, null, null, null, true),

  (brcgs_id, 'BRCGS-002', 'Food safety culture programme — documented and measured',
   'The site must have a documented programme to develop and maintain a positive food safety culture with measurable KPIs reviewed regularly.',
   'policy_control', 'Yellow',
   'BRCGS Food Issue 9, Clause 1.1.2 — Food Safety Culture',
   'food_safety', 'global', null, 'gi',
   'Provide the food safety culture plan including defined activities, responsible persons, KPIs, and last review results with trending.',
   null, null, null, null, true),

  (brcgs_id, 'BRCGS-003', 'Hazard and risk assessment for food safety',
   'A formal, documented hazard and risk assessment relevant to all products and processes must be in place and must be updated as required.',
   'policy_control', 'Red',
   'BRCGS Food Issue 9, Clause 2 — Food Safety Plan',
   'food_safety', 'global', null, 'gi',
   'Confirm the food safety plan / HACCP plan is current (reviewed within 12 months or after any change). Provide the review confirmation log.',
   null, null, null, null, true),

  (brcgs_id, 'BRCGS-004', 'Supplier approval and monitoring programme',
   'All suppliers of raw materials, ingredients, and packaging must be assessed for risk and approved before use. Ongoing monitoring must be in place.',
   'policy_control', 'Yellow',
   'BRCGS Food Issue 9, Clause 3.5 — Supplier and Raw Material Approval',
   'food_safety', 'global', null, 'gi',
   'Provide the approved supplier register entry for this supplier including risk categorisation, approval evidence (audit, certification, or questionnaire), and last review date.',
   null, null, null, null, true),

  (brcgs_id, 'BRCGS-005', 'Specifications — raw materials and finished products',
   'Specifications must exist for all raw materials, packaging, and finished products. They must be agreed with relevant parties and reviewed regularly.',
   'policy_control', 'Yellow',
   'BRCGS Food Issue 9, Clause 3.3 — Customer Focus, Communication and Review',
   'food_safety', 'global', null, 'gi',
   'Provide the current specification for this raw material or product. Confirm it is version-controlled, reviewed within 3 years, and covers all required parameters.',
   null, null, null, null, true),

  (brcgs_id, 'BRCGS-006', 'Internal audit schedule and completion',
   'A risk-based internal audit programme must be maintained. Audits must cover all activities within the scope of the BRCGS standard.',
   'policy_control', 'Yellow',
   'BRCGS Food Issue 9, Clause 3.4 — Internal Audits',
   'audit', 'global', null, 'gi',
   'Provide the internal audit schedule for the year and confirm audits are completed per plan. Provide the last three completed audit reports with CAPA tracking.',
   null, null, null, null, true),

  (brcgs_id, 'BRCGS-007', 'Full forward/backward traceability test',
   'A traceability system must be in place enabling the identification of all raw material batches within finished product batches and vice versa, completable within 4 hours.',
   'policy_control', 'Red',
   'BRCGS Food Issue 9, Clause 3.9 — Traceability',
   'food_safety', 'global', null, 'gi',
   'Provide the last traceability test report demonstrating a full forward and backward trace completed within the 4-hour requirement, including mass balance calculation.',
   null, null, null, null, true),

  (brcgs_id, 'BRCGS-008', 'Allergen risk assessment and cross-contact controls',
   'An allergen risk assessment must cover raw materials, rework, shared equipment/lines, cleaning validation, and labelling accuracy.',
   'policy_control', 'Red',
   'BRCGS Food Issue 9, Clause 5.3 — Allergen Control',
   'food_safety', 'global', null, 'gi',
   'Provide the allergen risk assessment and site allergen matrix. Confirm cleaning validation data for allergen removal is current and label accuracy review was completed.',
   null, null, null, null, true),

  (brcgs_id, 'BRCGS-009', 'Foreign body risk assessment and physical contaminant controls',
   'A documented foreign body risk assessment must cover all sources of physical contamination. Detection equipment must be validated at defined frequencies.',
   'policy_control', 'Yellow',
   'BRCGS Food Issue 9, Clause 4.10 — Foreign Body Detection and Control',
   'food_safety', 'global', null, 'gi',
   'Provide the foreign body risk assessment and detection equipment validation records (metal detector / X-ray test frequency, test pieces used, and last passed check).',
   null, null, null, null, true),

  (brcgs_id, 'BRCGS-010', 'Customer complaint trend analysis and response',
   'All customer complaints must be recorded. Trends must be analysed and root cause investigation conducted for any recurrence or significant issues.',
   'policy_control', 'Yellow',
   'BRCGS Food Issue 9, Clause 3.10 — Complaints Handling',
   'food_safety', 'global', null, 'gi',
   'Provide the complaint log for the last 12 months with trend analysis by category. Confirm any recurring issue has an active CAPA with targeted reduction KPI.',
   null, null, null, null, true)

ON CONFLICT (framework_id, control_code) DO NOTHING;

RAISE NOTICE 'Quality/GMP/Food Safety framework seed completed.';

END $$;
